### ISSUE TITLE
How to choose between Radians and Degrees? 

### ISSUE THREAD

**Issue by joserodpt** [gbenroscience/parserng-android#1]

**Comment by gbenroscience** [comment]
Hi @JoseGamerPT , the MathExpression class has the DRG field.

When DRG = 0 , all calculations are in degrees,
When DRG = 1 , all calculations are in rads,
When DRG = 2 , all calculations are in grads,



To switch between the various modes, do:
```

        MathExpression mep = new MathExpression("x=2;sin(x)");
         mep.setDRG(0);
        System.out.println("In degrees: "+ mep.solve());
         mep.setDRG(1);
        System.out.println("In rads: "+ mep.solve());
         mep.setDRG(2);
        System.out.println("In grads: "+ mep.solve());
```

**Comment by joserodpt** [comment]
Hi there!
Thank you for the explanation!

**Comment by joserodpt** [comment]
Another question:
If i set DRG to 1, which equals to Radians
an if i type sin(2π), it gives me: -2.449E-16 and it should give 0
how can i fix it?

**Comment by gbenroscience** [comment]
> Another question:
> If i set DRG to 1, which equals to Radians
> an if i type sin(2π), it gives me: -2.449E-16 and it should give 0
> how can i fix it?

This is a well known issue in computer science as relates to computations involving floating point numbers. [See here](https://stackoverflow.com/a/3962378/1845404)

There is no direct way to do this, from within the library currently.

You could get creative and do it programmatically though.

**Comment by joserodpt** [comment]
Okay thanks for the info! Very usefull.
